import React, { useState } from 'react';
import { View, Text, StyleSheet, Modal, TouchableOpacity, ScrollView, Alert, FlatList, Share, Image, Platform } from 'react-native';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { COLORS } from '../theme/colors';
import { useGuts } from '../context/GutsContext';
import { TransactionCard } from './TransactionCard';

export const PlayerDetailModal = ({ visible, onClose, player, onOpenAddMatch, onOpenSettle, onOpenTransfer, onEditPlayer }) => {
  const { transactions, settings, deletePlayer, getH2HStats, showToast, themeColors, toggleTransactionStatus, deleteTransaction } = useGuts();
  const [activeTab, setActiveTab] = useState('ANALYTICS'); // 'ANALYTICS' or 'LOGS'
  const symbol = settings.currencySymbol || '$';

  if (!player) return null;

  const playerTxs = transactions.filter(t => t.playerId === player.id);
  const h2h = getH2HStats ? getH2HStats(player.id) : {
    wins: 0, losses: 0, draws: 0, totalMatches: 0, winRate: 0, currentStreak: '-',
    biggestWinPoints: 0, biggestLossPoints: 0, biggestWinCash: 0, biggestLossCash: 0,
    totalMatchPointsWon: 0, totalMatchPointsLost: 0, avgPointsPerMatch: 0, recentMatches: []
  };

  const isOwesYou = player.netCashAmount > 0;
  const isYouOwe = player.netCashAmount < 0;
  const isSettled = player.netCashAmount === 0;
  const isLightBg = player.avatarColor === '#F9FAFB' || player.avatarColor === '#F59E0B' || player.avatarColor === '#D4AF37';

  const handleShareStatement = async () => {
    const streakText = h2h.streakCount > 0 
      ? `${h2h.streakCount} ${h2h.streakType === 'W' ? 'Win(s)' : 'Loss(es)'}`
      : 'None';

    const summary = `🎱 SNOOKER GUTS H2H STATEMENT 🎱\n` +
      `Opponent: ${player.name}\n` +
      `Record: ${h2h.wins}W - ${h2h.losses}L (${h2h.winRate}% Win Rate)\n` +
      `Current Streak: ${streakText}\n` +
      `Net Points: ${player.netGutsPoints > 0 ? '+' : ''}${player.netGutsPoints} Pts\n` +
      `Net Cash Balance: ${isOwesYou ? 'Owes You ' + symbol : isYouOwe ? 'You Owe ' + symbol : 'Settled ' + symbol}${Math.abs(player.netCashAmount).toFixed(2)}\n\n` +
      `Generated by Snooker Guts App`;

    try {
      await Share.share({ title: `H2H Statement - ${player.name}`, message: summary });
    } catch (e) {
      if (e.name === 'AbortError' || e.message?.includes('canceled') || e.message?.includes('cancelled')) {
        // Ignore user cancellation gracefully
        return;
      }
      console.error(e);
      showToast('Could not share statement', 'error');
    }
  };

  const handleDeletePlayerPrompt = () => {
    if (Platform.OS === 'web') {
      const confirmDelete = window.confirm(
        `Are you sure you want to delete ${player.name}? This will remove all their match history from your ledger.`
      );
      if (confirmDelete) {
        deletePlayer(player.id).then(() => {
          onClose();
        });
      }
      return;
    }

    Alert.alert(
      'Delete Opponent?',
      `Are you sure you want to delete ${player.name}? This will remove all their match history from your ledger.`,
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Delete', 
          style: 'destructive', 
          onPress: async () => {
            await deletePlayer(player.id);
            onClose();
          } 
        },
      ]
    );
  };

  const styles = getStyles(themeColors);

  return (
    <Modal visible={visible} animationType="slide" transparent={true}>

      <View style={styles.overlay}>
        <View style={[styles.container, { backgroundColor: themeColors.background }]}>
          {/* Header Bar */}
          <View style={[styles.header, { backgroundColor: themeColors.surface, borderBottomColor: themeColors.surfaceBorder }]}>
            <TouchableOpacity onPress={onClose} style={styles.backBtn}>
              <Ionicons name="chevron-back" size={24} color={themeColors.textPrimary} />
            </TouchableOpacity>

            <Text style={[styles.headerTitle, { color: themeColors.textPrimary }]}>Head-to-Head Ledger</Text>

            <View style={{ flexDirection: 'row', gap: 12 }}>
              <TouchableOpacity onPress={() => { onClose(); onEditPlayer(player); }} style={styles.deleteBtn}>
                <Ionicons name="create-outline" size={20} color={themeColors.textPrimary} />
              </TouchableOpacity>

              <TouchableOpacity onPress={handleShareStatement} style={styles.deleteBtn}>
                <Ionicons name="share-social-outline" size={20} color={themeColors.accentGold} />
              </TouchableOpacity>

              <TouchableOpacity onPress={handleDeletePlayerPrompt} style={styles.deleteBtn}>
                <Ionicons name="trash-outline" size={20} color={themeColors.payable} />
              </TouchableOpacity>
            </View>
          </View>

          {/* Profile Overview Card */}
          <View style={[styles.profileCard, { backgroundColor: themeColors.surface, borderColor: themeColors.surfaceBorder }]}>
            <View style={styles.profileTopRow}>
              <View style={[styles.avatar, { backgroundColor: player.avatarColor || themeColors.primary }]}>
                {player.avatarUri ? (
                  <Image source={{ uri: player.avatarUri }} style={styles.avatarImage} />
                ) : player.avatarIcon ? (
                  <MaterialCommunityIcons name={player.avatarIcon} size={26} color={isLightBg ? '#000' : '#FFF'} />
                ) : (
                  <Text style={[styles.avatarText, isLightBg && { color: '#000' }]}>
                    {player.name.charAt(0).toUpperCase()}
                  </Text>
                )}
              </View>

              <View style={styles.profileMeta}>
                <Text style={[styles.playerName, { color: themeColors.textPrimary }]}>{player.name}</Text>
                {player.phone ? (
                  <View style={styles.phoneRow}>
                    <Ionicons name="call-outline" size={12} color={themeColors.accentGold} />
                    <Text style={[styles.phoneText, { color: themeColors.accentGold }]}>{player.phone}</Text>
                  </View>
                ) : null}
                {player.notes ? (
                  <Text style={[styles.notesText, { color: themeColors.textMuted }]}>{player.notes}</Text>
                ) : null}
              </View>
            </View>

            {/* Financial Summary */}
            <View style={styles.summaryRow}>
              <View style={[styles.summaryBox, { backgroundColor: themeColors.surfaceLight }]}>
                <Text style={[styles.summaryBoxLabel, { color: themeColors.textMuted }]}>GUTS POINTS</Text>
                <Text style={[
                  styles.summaryBoxVal,
                  player.netGutsPoints > 0 && { color: themeColors.receivable },
                  player.netGutsPoints < 0 && { color: themeColors.payable },
                ]}>
                  {player.netGutsPoints > 0 ? `+${player.netGutsPoints}` : player.netGutsPoints} Pts
                </Text>
              </View>

              <View style={[styles.summaryBox, styles.summaryBoxDivider, { backgroundColor: themeColors.surfaceLight, borderColor: themeColors.surfaceBorder }]}>
                <Text style={[styles.summaryBoxLabel, { color: themeColors.textMuted }]}>NET CASH BALANCE</Text>
                <Text style={[
                  styles.summaryBoxVal,
                  isOwesYou && { color: themeColors.receivable },
                  isYouOwe && { color: themeColors.payable },
                  isSettled && { color: themeColors.settled },
                ]}>
                  {isOwesYou ? `+${symbol}` : isYouOwe ? `-${symbol}` : symbol}
                  {Math.abs(player.netCashAmount).toFixed(2)}
                </Text>
              </View>
            </View>

            {/* Quick Action Buttons */}
            <View style={styles.actionRow}>
              {!isSettled && (
                <TouchableOpacity 
                  style={[styles.settleBtn, { backgroundColor: themeColors.accentGold }]}
                  onPress={() => { onClose(); onOpenSettle(player); }}
                >
                  <Ionicons name="checkmark-done" size={16} color="#000" />
                  <Text style={styles.settleBtnText}>Settle Up</Text>
                </TouchableOpacity>
              )}

              <TouchableOpacity 
                style={[styles.addMatchBtn, { backgroundColor: themeColors.surfaceLight, borderColor: themeColors.surfaceBorder }]}
                onPress={() => { onClose(); onOpenAddMatch(player); }}
              >
                <Ionicons name="add-circle-outline" size={16} color={themeColors.accentGold} />
                <Text style={[styles.addMatchBtnText, { color: themeColors.accentGold }]}>+ Match</Text>
              </TouchableOpacity>

              <TouchableOpacity 
                style={[styles.transferBtn, { backgroundColor: themeColors.surfaceLight, borderColor: themeColors.surfaceBorder }]}
                onPress={() => { onClose(); onOpenTransfer(player.id); }}
              >
                <MaterialCommunityIcons name="swap-horizontal" size={16} color={themeColors.textPrimary} />
                <Text style={[styles.transferBtnText, { color: themeColors.textPrimary }]}>Transfer</Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Segmented View Switcher */}
          <View style={[styles.tabContainer, { backgroundColor: themeColors.surfaceLight }]}>
            <TouchableOpacity 
              style={[styles.tabSegment, activeTab === 'ANALYTICS' && { backgroundColor: themeColors.accentGold }]}
              onPress={() => setActiveTab('ANALYTICS')}
              activeOpacity={0.8}
            >
              <MaterialCommunityIcons name="chart-box" size={16} color={activeTab === 'ANALYTICS' ? '#000' : themeColors.textMuted} />
              <Text style={[styles.tabSegmentText, { color: themeColors.textMuted }, activeTab === 'ANALYTICS' && { color: '#000', fontWeight: '800' }]}>
                H2H ANALYTICS
              </Text>
            </TouchableOpacity>

            <TouchableOpacity 
              style={[styles.tabSegment, activeTab === 'LOGS' && { backgroundColor: themeColors.accentGold }]}
              onPress={() => setActiveTab('LOGS')}
              activeOpacity={0.8}
            >
              <Ionicons name="list" size={16} color={activeTab === 'LOGS' ? '#000' : themeColors.textMuted} />
              <Text style={[styles.tabSegmentText, { color: themeColors.textMuted }, activeTab === 'LOGS' && { color: '#000', fontWeight: '800' }]}>
                MATCH LOGS ({playerTxs.length})
              </Text>
            </TouchableOpacity>
          </View>

          {/* Body Section based on Active Tab */}
          {activeTab === 'ANALYTICS' ? (
            <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 20 }}>
              {/* Win Rate & Record Banner */}
              <View style={styles.h2hCard}>
                <View style={styles.winRateRow}>
                  <View style={styles.winRateCircle}>
                    <Text style={styles.winRateValue}>{h2h.winRate}%</Text>
                    <Text style={styles.winRateSub}>WIN RATE</Text>
                  </View>

                  <View style={styles.winRecordMeta}>
                    <Text style={styles.h2hCardTitle}>MATCH RECORD</Text>
                    <Text style={styles.h2hRecordText}>
                      <Text style={{ color: COLORS.receivable, fontWeight: '800' }}>{h2h.wins} Wins</Text>
                      {'  •  '}
                      <Text style={{ color: COLORS.payable, fontWeight: '800' }}>{h2h.losses} Losses</Text>
                      {h2h.draws > 0 ? `  •  ${h2h.draws} Draws` : ''}
                    </Text>
                    <Text style={styles.totalGamesSub}>Total {h2h.totalMatches} matches played</Text>
                  </View>
                </View>

                {/* Progress Bar for Win Rate */}
                <View style={styles.progressTrack}>
                  <View style={[styles.progressFill, { width: `${Math.min(100, Math.max(0, h2h.winRate))}%` }]} />
                </View>

                {/* Form & Recent 5 Matches */}
                <View style={styles.formRow}>
                  <Text style={styles.formLabel}>RECENT FORM:</Text>
                  {h2h.recentMatches.length === 0 ? (
                    <Text style={styles.noFormText}>No matches recorded yet</Text>
                  ) : (
                    <View style={styles.pillRow}>
                      {h2h.recentMatches.map((m, idx) => (
                        <View 
                          key={m.id || idx} 
                          style={[
                            styles.formPill,
                            m.result === 'W' && styles.formPillWin,
                            m.result === 'L' && styles.formPillLoss,
                          ]}
                        >
                          <Text style={[
                            styles.formPillText,
                            m.result === 'W' && styles.formPillTextWin,
                            m.result === 'L' && styles.formPillTextLoss,
                          ]}>
                            {m.result}
                          </Text>
                        </View>
                      ))}
                    </View>
                  )}

                  {/* Active Streak Badge */}
                  {h2h.streakCount > 0 ? (
                    <View style={[
                      styles.streakBadge,
                      h2h.streakType === 'W' ? styles.streakBadgeWin : styles.streakBadgeLoss,
                    ]}>
                      <Text style={[
                        styles.streakBadgeText,
                        h2h.streakType === 'W' ? styles.streakBadgeTextWin : styles.streakBadgeTextLoss,
                      ]}>
                        {h2h.streakCount} {h2h.streakType === 'W' ? 'WIN STREAK 🔥' : 'LOSS STREAK ❄️'}
                      </Text>
                    </View>
                  ) : null}
                </View>
              </View>

              {/* Performance & High Records Grid */}
              <Text style={styles.sectionHeader}>HEAD-TO-HEAD RECORDS</Text>
              <View style={styles.recordsGrid}>
                {/* Biggest Win */}
                <View style={styles.recordCard}>
                  <View style={styles.recordIconBgWin}>
                    <Ionicons name="trophy-outline" size={18} color={COLORS.receivable} />
                  </View>
                  <Text style={styles.recordLabel}>BIGGEST MATCH WIN</Text>
                  <Text style={styles.recordValWin}>
                    {h2h.biggestWinPoints > 0 ? `+${h2h.biggestWinPoints} Pts` : 'None'}
                  </Text>
                  {h2h.biggestWinCash > 0 && (
                    <Text style={styles.recordSub}>+{symbol}{h2h.biggestWinCash.toFixed(2)} cash value</Text>
                  )}
                </View>

                {/* Biggest Loss */}
                <View style={styles.recordCard}>
                  <View style={styles.recordIconBgLoss}>
                    <Ionicons name="trending-down-outline" size={18} color={COLORS.payable} />
                  </View>
                  <Text style={styles.recordLabel}>BIGGEST MATCH LOSS</Text>
                  <Text style={styles.recordValLoss}>
                    {h2h.biggestLossPoints > 0 ? `-${h2h.biggestLossPoints} Pts` : 'None'}
                  </Text>
                  {h2h.biggestLossCash > 0 && (
                    <Text style={styles.recordSub}>-{symbol}{h2h.biggestLossCash.toFixed(2)} cash value</Text>
                  )}
                </View>
              </View>

              <View style={[styles.recordsGrid, { marginTop: 10 }]}>
                {/* Total Points Won vs Lost */}
                <View style={styles.recordCard}>
                  <View style={styles.recordIconBgNeutral}>
                    <MaterialCommunityIcons name="swap-vertical-bold" size={18} color={COLORS.accentGold} />
                  </View>
                  <Text style={styles.recordLabel}>POINTS RATIO</Text>
                  <Text style={styles.recordValNeutral}>
                    +{h2h.totalMatchPointsWon} / -{h2h.totalMatchPointsLost}
                  </Text>
                  <Text style={styles.recordSub}>Pts Won vs Pts Lost</Text>
                </View>

                {/* Average Points Per Match */}
                <View style={styles.recordCard}>
                  <View style={styles.recordIconBgNeutral}>
                    <MaterialCommunityIcons name="calculator-variant" size={18} color={COLORS.accentGold} />
                  </View>
                  <Text style={styles.recordLabel}>AVG PTS / MATCH</Text>
                  <Text style={styles.recordValNeutral}>
                    {parseFloat(h2h.avgPointsPerMatch) > 0 ? `+${h2h.avgPointsPerMatch}` : h2h.avgPointsPerMatch}
                  </Text>
                  <Text style={styles.recordSub}>Net avg per game</Text>
                </View>
              </View>
            </ScrollView>
          ) : (
            /* Match Logs Tab */
            <>
              <Text style={styles.sectionHeader}>MATCH & PAYMENT HISTORY ({playerTxs.length})</Text>

              {playerTxs.length === 0 ? (
                <View style={styles.emptyState}>
                  <MaterialCommunityIcons name="billiards-rack" size={40} color={COLORS.surfaceBorder} />
                  <Text style={styles.emptyTitle}>No Guts Games Logged Yet</Text>
                  <Text style={styles.emptySub}>Tap "+ Match" to record points won or lost against {player.name}.</Text>
                </View>
              ) : (
                <FlatList
                  data={playerTxs}
                  keyExtractor={item => item.id}
                  renderItem={({ item }) => (
                    <TransactionCard
                      transaction={item}
                      onToggleStatus={toggleTransactionStatus}
                      onDelete={deleteTransaction}
                    />
                  )}
                  contentContainerStyle={{ paddingBottom: 20 }}
                  showsVerticalScrollIndicator={false}
                />
              )}
            </>
          )}
        </View>
      </View>
    </Modal>
  );
};

const getStyles = (COLORS) => StyleSheet.create({

  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: COLORS.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    height: '92%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginHorizontal: -20,
    marginTop: -20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  backBtn: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  deleteBtn: {
    padding: 4,
  },
  profileCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.surfaceBorder,
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 14,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  avatarText: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: '800',
  },
  profileMeta: {
    flex: 1,
  },
  playerName: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  phoneText: {
    fontSize: 12,
    color: COLORS.accentGold,
    fontWeight: '600',
  },
  notesText: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  summaryRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.surfaceLight,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  summaryBox: {
    flex: 1,
    alignItems: 'center',
  },
  summaryBoxDivider: {
    borderLeftWidth: 1,
    borderLeftColor: COLORS.surfaceBorder,
  },
  summaryBoxLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  summaryBoxVal: {
    fontSize: 18,
    fontWeight: '800',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  settleBtn: {
    flex: 1,
    backgroundColor: COLORS.accentGold,
    paddingVertical: 10,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  settleBtnText: {
    color: '#000',
    fontWeight: '800',
    fontSize: 13,
  },
  addMatchBtn: {
    flex: 1,
    backgroundColor: COLORS.surfaceLight,
    paddingVertical: 10,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.accentGold,
  },
  addMatchBtnText: {
    color: COLORS.accentGold,
    fontWeight: '700',
    fontSize: 13,
  },
  transferBtn: {
    flex: 1,
    backgroundColor: COLORS.surfaceLight,
    paddingVertical: 10,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.surfaceBorder,
  },
  transferBtnText: {
    color: COLORS.textPrimary,
    fontWeight: '700',
    fontSize: 13,
  },

  // Segmented Tabs
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.surfaceBorder,
  },
  tabSegment: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    gap: 6,
  },
  tabSegmentActive: {
    backgroundColor: COLORS.accentGold,
  },
  tabSegmentText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMuted,
  },
  tabSegmentTextActive: {
    color: '#000',
    fontWeight: '800',
  },

  // H2H Analytics View
  h2hCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.surfaceBorder,
    marginBottom: 16,
  },
  winRateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 14,
  },
  winRateCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: COLORS.primaryDark,
    borderWidth: 2,
    borderColor: COLORS.accentGold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  winRateValue: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.accentGold,
  },
  winRateSub: {
    fontSize: 8,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 0.5,
  },
  winRecordMeta: {
    flex: 1,
  },
  h2hCardTitle: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  h2hRecordText: {
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  totalGamesSub: {
    fontSize: 11,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  progressTrack: {
    height: 6,
    backgroundColor: COLORS.surfaceBorder,
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 14,
  },
  progressFill: {
    height: '100%',
    backgroundColor: COLORS.accentGold,
    borderRadius: 3,
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.surfaceBorder,
  },
  formLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.5,
  },
  noFormText: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontStyle: 'italic',
  },
  pillRow: {
    flexDirection: 'row',
    gap: 4,
  },
  formPill: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: COLORS.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formPillWin: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 1,
    borderColor: COLORS.receivable,
  },
  formPillLoss: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderWidth: 1,
    borderColor: COLORS.payable,
  },
  formPillText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
  },
  formPillTextWin: {
    color: COLORS.receivable,
  },
  formPillTextLoss: {
    color: COLORS.payable,
  },
  streakBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginLeft: 'auto',
  },
  streakBadgeWin: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 1,
    borderColor: COLORS.receivable,
  },
  streakBadgeLoss: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderWidth: 1,
    borderColor: COLORS.payable,
  },
  streakBadgeText: {
    fontSize: 10,
    fontWeight: '800',
  },
  streakBadgeTextWin: {
    color: COLORS.receivable,
  },
  streakBadgeTextLoss: {
    color: COLORS.payable,
  },

  // Record Cards Grid
  recordsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  recordCard: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.surfaceBorder,
  },
  recordIconBgWin: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  recordIconBgLoss: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  recordIconBgNeutral: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  recordLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  recordValWin: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.receivable,
  },
  recordValLoss: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.payable,
  },
  recordValNeutral: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  recordSub: {
    fontSize: 10,
    color: COLORS.textMuted,
    marginTop: 2,
  },

  sectionHeader: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textSecondary,
    letterSpacing: 1,
    marginBottom: 10,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginTop: 10,
  },
  emptySub: {
    fontSize: 12,
    color: COLORS.textMuted,
    textAlign: 'center',
    marginTop: 4,
    paddingHorizontal: 20,
  },
});

